#! /bin/bash
# Author: Cmdr Magic Sumadartson, 2014
#
# Please send feedback to shtong@mm.st
#
# /etc/init.d/feeder
#
### BEGIN INIT INFO
# Provides: feeder
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: EMDN subscriber
# Description:    Subscribes to the EMDN data service and saves trading data into a MongoDB database
### END INIT INFO

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon
    python /usr/share/feeder/feeder.py start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    python /usr/share/feeder/feeder.py stop
    ;;
  restart)
    echo "Restarting server"
    python /usr/share/feeder/feeder.py restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/feeder {start|stop|restart}"
    exit 1
    ;;
esac

exit 0