//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyConfiguration("Deploy")]
[assembly: System.Reflection.AssemblyVersion("1.0.16.40675")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.16.40675")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.16.40675")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyConfiguration = "Deploy";
    
    internal const string AssemblyVersion = "1.0.16.40675";
    
    internal const string AssemblyFileVersion = "1.0.16.40675";
    
    internal const string AssemblyInformationalVersion = "1.0.16.40675";
    
    private ThisAssembly() {
    }
}
